API_TOKEN = ""
WEBHOOK_URL = ""
NGINX_SUBPATH = ""
POLLING = True
ALLOWED_FONTS = [
    "3d_diagonal",
    "alligator2",
    "alpha",
    "amcslash",
    "blocks",
    "bolger",
    "broadway",
    "calgphy2",
    "chiseled",
    "computer",
    "cosmic",
    "defleppard",
    "doh",
    "fraktur",
    "georgia11",
    "impossible",
    "isometric4",
    "knob",
    "lean",
    "p_s_h_m_",
    "poison",
    "roman___",
    "roman",
    "rozzo",
    "sblood",
    "smisome1",
    "space_op",
    "speed",
    "sub-zero",
    "swampland",
    "timesofl",
    "trashman",
    "usaflag",
    "whimsy"
]
